declare namespace svelteHTML {
  type UtilityNames =
    | 'p'
    | 'm'
    | 'w'
    | 'min-w'
    | 'max-w'
    | 'min-h'
    | 'max-h'
    | 'h'
    | 'z'
    | 'border'
    | 'grid'
    | 'flex'
    | 'bg'
    | 'text'
    | 'font'
    | 'opacity'
    | 'animate'
    | 'transition'
    | 'transform'
    | 'align'
    | 'justify'
    | 'items'
    | 'block'
    | 'content'
    | 'pos'
    | 'box'
    | 'caret'
    | 'isolation'
    | 'object'
    | 'overflow'
    | 'overscroll'
    | 'resize'
    | 'underline'
    | 'list'
    | 'gradient'
    | 'divide'
    | 'gap'
    | 'ring'
    | 'icon'
    | 'container'
    | 'space'
    | 'table'
    | 'order'
    | 'place'
    | 'display'
    | 'shadow'
    | 'blend'
    | 'filter'
    | 'backdrop'
    | 'cursor'
    | 'outline'
    | 'select'
    | 'appearance'
    | 'pointer-events';

  type VariantNames =
    | 'hover'
    | 'active'
    | 'focus'
    | 'enabled'
    | 'dark'
    | 'light'
    | 'sm'
    | 'lg'
    | 'md'
    | 'xl'
    | 'xxl'
    | 'first'
    | 'last'
    | 'child'
    | 'root'
    | 'before'
    | 'after'
    | 'all';

  type AttributifyNames<Prefix extends string = ''> =
    | `${Prefix}${UtilityNames}`
    | `${Prefix}${VariantNames}`;
  // | `${Prefix}${VariantNames}:${UtilityNames}`;

  type AttributifyAttributes = Partial<Record<AttributifyNames, string>>;

  type HTMLAttributes = AttributifyAttributes;
}
